# SConstruct
# Copyright (C) 1999-2022 Eicke Godehardt

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


Import ('env install_dir tar_file prefix')

# test = env.Program ('test', ['test-autostart.c', 'autostart.c'])

glosung = env.Program ('glosung', ['glosung.c', 'parser.c', 'autostart.c',
             'download.c', 'collections.c', 'about.c', 'util.c', 'settings.c', 'resources.c'])
losung  = env.Program ('losung', ['losung.c', 'parser.c', 'util.c', 'settings.c'])
env.Install (dir = install_dir + prefix + '/bin', source = [losung, glosung])

if env['PLATFORM'] != 'win32':
	env.Tar (tar_file, ['SConscript',
                    'about.c',
                    'about.h',
                    'autostart.c',
                    'autostart.h',
                    'download.c',
                    'download.h',
                    'glosung.c',
                    'losung.c',
                    'collections.c',
                    'collections.h',
                    'parser.c',
                    'parser.h',
                    'settings.c',
                    'settings.h',
                    'util.c',
                    'util.h'])

gresource = env.Command ('resources.c', ['#/glosung.gresource.xml',
                                   '#/ui/add_language.ui',
                                   '#/ui/glosung.ui',
                                   '#/ui/language_manager.ui',
                                   '#/ui/preferences.ui',
                                   '#/ui/warning_dialog.ui',
                                   '#/ui/style.css',
                                   '#/ui/icons/angle-left-solid.png',
                                   '#/ui/icons/angle-left-solid-white.png',
                                   '#/ui/icons/angle-right-solid.png',
                                   '#/ui/icons/angle-right-solid-white.png',
                                   '#/ui/icons/angles-down-solid.png',
                                   '#/ui/icons/angles-down-solid-white.png',
                                   '#/ui/icons/angles-left-solid.png',
                                   '#/ui/icons/angles-left-solid-white.png',
                                   '#/ui/icons/bars-solid.png',
                                   '#/ui/icons/bars-solid-white.png',
                                   '#/ui/icons/calendar-alt-regular.png',
                                   '#/ui/icons/calendar-alt-regular-white.png',
                                   '#/ui/icons/clone-regular.png',
                                   '#/ui/icons/clone-regular-white.png',
                                   '#/ui/icons/gear-solid.png',
                                   '#/ui/icons/gear-solid-white.png',
                                   '#/ui/icons/question-circle-regular.png',
                                   '#/ui/icons/question-circle-regular-white.png'],
          "glib-compile-resources --generate-source --target=$TARGET $SOURCE");
#env.AlwaysBuild(gresource)
