name: C CI Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: scons debhelper intltool libgtk-4-dev libadwaita-1-dev libxml2-dev libcurl4-gnutls-dev libgconf2-dev gettext
          version: 1.0

      - name: Install jq and awk
        run: |
           sudo apt-get install -y jq
           sudo apt-get install -y gawk
           
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y scons debhelper intltool libgtk-4-dev libadwaita-1-dev libxml2-dev libcurl4-gnutls-dev libgconf2-dev gettext
          sudo apt-get install -y python3-pip
          pip install opencv-contrib-python
          pip install opencv-python
          pip install -U Flask

      - name: Install SCons
        run: sudo apt-get install scons

      - name: Build
        run: |
          scons

      - name: Set up GCC
        uses: Dup4/actions-setup-gcc@v1

      - name: Install binutils
        run: sudo apt-get install binutils

      - name: Check if all necessary files are present
        run: |
          ls ./
          if [ ! -f flatpak.json ]; then echo "Manifest file not found!"; exit 1; fi

  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Set up Flatpak environment
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y flatpak-builder flatpak
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.gnome.Sdk//43
          sudo flatpak update -y
          sudo flatpak install -y flathub org.freedesktop.Platform.GL.default//23.08
          sudo apt-get install -y

      - name: Flatpak Builder
        uses: flatpak/flatpak-github-actions@v6.3

      - name: Upload Flatpak package to GitHub Releases
        uses: actions/upload-artifact@v2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          name: flatpak-package
          path: path/to/your/flatpak-packag