name: C CI Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: scons debhelper intltool libgtk-4-dev libadwaita-1-dev libxml2-dev libcurl4-gnutls-dev libgconf2-dev gettext
          version: 1.0

      - name: Install jq and awk
        run: |
           sudo apt-get install -y jq
           sudo apt-get install -y gawk
           
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install SCons python-gettext
      - name: Build
        run: |
          scons 

      - name: Install Flatpak Builder
        run: sudo apt-get install flatpak-builder 

      - name: Create ZIP file
        run: zip -r glosung.zip . -x ".git/*" ".github/*" "TODO" "screenshot.png" ".gitignore" "glosung.svg" "herrnhut.svg" "README.md" "INSTALL" "org.flatpak.glosung.yaml" "org.gnome.zbrown.glosung.json" "publish_flatpak.sh" "yamltest.yml" "publish_flatpak.sh" "CHANGELOG.md"

      - name: Create tar file
        run: zip -r glosung.tar.xz . -x ".git/*" ".github/*" "TODO" "screenshot.png" ".gitignore" "glosung.svg" "herrnhut.svg" "README.md" "INSTALL" "org.flatpak.glosung.yaml" "org.gnome.zbrown.glosung.json" "publish_flatpak.sh" "yamltest.yml" "publish_flatpak.sh" "CHANGELOG.md"

      - name: Install Flatpak
        run: |
          sudo apt-get install -y flatpak

      - name: Build and Bundle Flatpak
        run: |
          flatpak-builder --force-clean --install --user --verbose --repo=flatpak-repo org.gnome.zbrown.Palette.json

      - name: Install and Run Flatpak
        run: |
          flatpak install --user --bundle glosung.tar.xz
          flatpak run --user --bundle glosung.tar.xz