name: Build and publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build and publish
        run: |
          flatpak-builder --sdk --no-x11 build MyApp.flatpak
          flatpak-builder --sdk --no-x11 publish MyApp.flatpak